spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url: 
spring.datasource.username: mfpcvwfsqgocvc
spring.datasource.password: a7c318a503970517548875da76b00d47a66afea227dad97309215557f855efe1