
# ----------------------------------------
# DATASOURCE PARAMETERS
# ----------------------------------------
spring:
  banner:
    location: banner.txt
  resources:
    chain:
      cache: false
  jpa:
    hibernate:
      ddl-auto: none   
      show-sql: true
   
  h2.console.enabled: true
  h2.console.settings.trace: false
  h2.console.settings.web-allow-others: false
  
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/db.changelog.xml 
    user: sa
    password:
    contexts: DESA

springdoc:
   api-docs: 
      path: /doc/api-docs
      enabled: true
   swagger-ui:
      path: /doc/swagger-ui.html
      enabled: true