
# ----------------------------------------
# DATASOURCE PARAMETERS
# ----------------------------------------
spring:
  banner:
    location: banner.txt
  resources:
    chain:
      cache: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none   
      

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase/db.changelog.xml 
    contexts: DESA

springdoc:
   api-docs: 
      path: /doc/api-docs
      enabled: true
   swagger-ui:
      path: /doc/swagger-ui.html
      enabled: true
